### ISSUE TITLE
Server Error (500)

### ISSUE THREAD

**Issue by duronxx** [welliamcao/OpsManage#330]
请问下是那里出问题了？

ops_web     | The above exception was the direct cause of the following exception:
ops_web     | 
ops_web     | Traceback (most recent call last):
ops_web     |   File "manage.py", line 23, in <module>
ops_web     |     execute_from_command_line(sys.argv)
ops_web     |   File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
ops_web     |     utility.execute()
ops_web     |   File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
ops_web     |     self.fetch_command(subcommand).run_from_argv(self.argv)
ops_web     |   File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
ops_web     |     self.execute(*args, **cmd_options)
ops_web     |   File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
ops_web     |     output = self.handle(*args, **options)
ops_web     |   File "/usr/local/lib/python3.6/site-packages/django/core/management/commands/loaddata.py", line 72, in handle
ops_web     |     self.loaddata(fixture_labels)
ops_web     |   File "/usr/local/lib/python3.6/site-packages/django/core/management/commands/loaddata.py", line 114, in loaddata
ops_web     |     self.load_label(fixture_label)
ops_web     |   File "/usr/local/lib/python3.6/site-packages/django/core/management/commands/loaddata.py", line 181, in load_label
ops_web     |     obj.save(using=self.using)
ops_web     |   File "/usr/local/lib/python3.6/site-packages/django/core/serializers/base.py", line 223, in save
ops_web     |     models.Model.save_base(self.object, using=using, raw=True, **kwargs)
ops_web     |   File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 779, in save_base
ops_web     |     force_update, using, update_fields,
ops_web     |   File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 851, in _save_table
ops_web     |     forced_update)
ops_web     |   File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 900, in _do_update
ops_web     |     return filtered._update(values) > 0
ops_web     |   File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 760, in _update
ops_web     |     return query.get_compiler(self.db).execute_sql(CURSOR)
ops_web     |   File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1469, in execute_sql
ops_web     |     cursor = super().execute_sql(result_type)
ops_web     |   File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1140, in execute_sql
ops_web     |     cursor.execute(sql, params)
ops_web     |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
ops_web     |     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
ops_web     |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
ops_web     |     return executor(sql, params, many, context)
ops_web     |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
ops_web     |     return self.cursor.execute(sql, params)
ops_web     |   File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
ops_web     |     raise dj_exc_value.with_traceback(traceback) from exc_value
ops_web     |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
ops_web     |     return self.cursor.execute(sql, params)
ops_web     |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
ops_web     |     return self.cursor.execute(query, args)
ops_web     |   File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 250, in execute
ops_web     |     self.errorhandler(self, exc, value)
ops_web     |   File "/usr/local/lib/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
ops_web     |     raise errorvalue
ops_web     |   File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 247, in execute
ops_web     |     res = self._query(query)
ops_web     |   File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 412, in _query
ops_web     |     rowcount = self._do_query(q)
ops_web     |   File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 375, in _do_query
ops_web     |     db.query(q)
ops_web     |   File "/usr/local/lib/python3.6/site-packages/MySQLdb/connections.py", line 276, in query
ops_web     |     _mysql.connection.query(self, query)
ops_web     | django.db.utils.ProgrammingError: Problem installing fixture '/data/apps/opsmanage/docker/superuser.json': Could not load auth.User(pk=1): (1146, "Table 'opsmanage.auth_user' doesn't exist")
ops_web     | Unlinking stale socket /tmp/supervisor.sock
ops_web     | 2021-11-08 20:34:26 [INFO] server.py[line:106] HTTP/2 support not enabled (install the http2 and tls Twisted extras)
ops_web     | 2021-11-08 20:34:26 [INFO] server.py[line:113] Configuring endpoint tcp:port=8000:interface=0.0.0.0
ops_web     | 2021-11-08 20:34:26 [INFO] server.py[line:144] Listening on TCP address 0.0.0.0:8000
ops_web     | 2021-11-08 20:35:21 [INFO] runserver.py[line:147] HTTP GET / 302 [0.05, 192.168.0.240:3204]
ops_web     | 2021-11-08 20:35:21 [ERROR] runserver.py[line:154] HTTP GET /login/?next=/ 500 [0.05, 192.168.0.240:3204]
ops_web     | 2021-11-08 20:39:41 [INFO] runserver.py[line:147] HTTP GET / 302 [0.01, 192.168.0.240:4576]
ops_web     | 2021-11-08 20:39:41 [ERROR] runserver.py[line:154] HTTP GET /login/?next=/ 500 [0.01, 192.168.0.240:4576]
ops_web     | 2021-11-08 20:39:41 [INFO] runserver.py[line:147] HTTP GET / 302 [0.00, 192.168.0.240:4576]
ops_web     | 2021-11-08 20:39:41 [ERROR] runserver.py[line:154] HTTP GET /login/?next=/ 500 [0.01, 192.168.0.240:4576]

**Comment by welliamcao** [comment]
表不存在，你用docker部署的吗？



发自我的iPhone


------------------ Original ------------------
From: duronxx ***@***.***&gt;
Date: Mon,Nov 8,2021 8:51 PM
To: welliamcao/OpsManage ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [welliamcao/OpsManage] Server Error (500) (Issue #330)





 
请问下是那里出问题了？
 
ops_web     | The above exception was the direct cause of the following exception:
 ops_web     |
 ops_web     | Traceback (most recent call last):
 ops_web     |   File "manage.py", line 23, in 
 ops_web     |     execute_from_command_line(sys.argv)
 ops_web     |   File "/usr/local/lib/python3.6/site-packages/django/core/management/init.py", line 381, in execute_from_command_line
 ops_web     |     utility.execute()
 ops_web     |   File "/usr/local/lib/python3.6/site-packages/django/core/management/init.py", line 375, in execute
 ops_web     |     self.fetch_command(subcommand).run_from_argv(self.argv)
 ops_web     |   File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
 ops_web     |     self.execute(*args, **cmd_options)
 ops_web     |   File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
 ops_web     |     output = self.handle(*args, **options)
 ops_web     |   File "/usr/local/lib/python3.6/site-packages/django/core/management/commands/loaddata.py", line 72, in handle
 ops_web     |     self.loaddata(fixture_labels)
 ops_web     |   File "/usr/local/lib/python3.6/site-packages/django/core/management/commands/loaddata.py", line 114, in loaddata
 ops_web     |     self.load_label(fixture_label)
 ops_web     |   File "/usr/local/lib/python3.6/site-packages/django/core/management/commands/loaddata.py", line 181, in load_label
 ops_web     |     obj.save(using=self.using)
 ops_web     |   File "/usr/local/lib/python3.6/site-packages/django/core/serializers/base.py", line 223, in save
 ops_web     |     models.Model.save_base(self.object, using=using, raw=True, **kwargs)
 ops_web     |   File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 779, in save_base
 ops_web     |     force_update, using, update_fields,
 ops_web     |   File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 851, in _save_table
 ops_web     |     forced_update)
 ops_web     |   File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 900, in _do_update
 ops_web     |     return filtered._update(values) &gt; 0
 ops_web     |   File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 760, in _update
 ops_web     |     return query.get_compiler(self.db).execute_sql(CURSOR)
 ops_web     |   File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1469, in execute_sql
 ops_web     |     cursor = super().execute_sql(result_type)
 ops_web     |   File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1140, in execute_sql
 ops_web     |     cursor.execute(sql, params)
 ops_web     |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
 ops_web     |     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
 ops_web     |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
 ops_web     |     return executor(sql, params, many, context)
 ops_web     |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
 ops_web     |     return self.cursor.execute(sql, params)
 ops_web     |   File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 89, in exit
 ops_web     |     raise dj_exc_value.with_traceback(traceback) from exc_value
 ops_web     |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
 ops_web     |     return self.cursor.execute(sql, params)
 ops_web     |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
 ops_web     |     return self.cursor.execute(query, args)
 ops_web     |   File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 250, in execute
 ops_web     |     self.errorhandler(self, exc, value)
 ops_web     |   File "/usr/local/lib/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
 ops_web     |     raise errorvalue
 ops_web     |   File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 247, in execute
 ops_web     |     res = self._query(query)
 ops_web     |   File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 412, in _query
 ops_web     |     rowcount = self._do_query(q)
 ops_web     |   File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 375, in _do_query
 ops_web     |     db.query(q)
 ops_web     |   File "/usr/local/lib/python3.6/site-packages/MySQLdb/connections.py", line 276, in query
 ops_web     |     _mysql.connection.query(self, query)
 ops_web     | django.db.utils.ProgrammingError: Problem installing fixture '/data/apps/opsmanage/docker/superuser.json': Could not load auth.User(pk=1): (1146, "Table 'opsmanage.auth_user' doesn't exist")
 ops_web     | Unlinking stale socket /tmp/supervisor.sock
 ops_web     | 2021-11-08 20:34:26 [INFO] server.py[line:106] HTTP/2 support not enabled (install the http2 and tls Twisted extras)
 ops_web     | 2021-11-08 20:34:26 [INFO] server.py[line:113] Configuring endpoint tcp:port=8000:interface=0.0.0.0
 ops_web     | 2021-11-08 20:34:26 [INFO] server.py[line:144] Listening on TCP address 0.0.0.0:8000
 ops_web     | 2021-11-08 20:35:21 [INFO] runserver.py[line:147] HTTP GET / 302 [0.05, 192.168.0.240:3204]
 ops_web     | 2021-11-08 20:35:21 [ERROR] runserver.py[line:154] HTTP GET /login/?next=/ 500 [0.05, 192.168.0.240:3204]
 ops_web     | 2021-11-08 20:39:41 [INFO] runserver.py[line:147] HTTP GET / 302 [0.01, 192.168.0.240:4576]
 ops_web     | 2021-11-08 20:39:41 [ERROR] runserver.py[line:154] HTTP GET /login/?next=/ 500 [0.01, 192.168.0.240:4576]
 ops_web     | 2021-11-08 20:39:41 [INFO] runserver.py[line:147] HTTP GET / 302 [0.00, 192.168.0.240:4576]
 ops_web     | 2021-11-08 20:39:41 [ERROR] runserver.py[line:154] HTTP GET /login/?next=/ 500 [0.01, 192.168.0.240:4576]
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by duronxx** [comment]
是的，数据库的表吗。


---Original---
From: ***@***.***&gt;
Date: Mon, Nov 8, 2021 21:07 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [welliamcao/OpsManage] Server Error (500) (Issue #330)




 表不存在，你用docker部署的吗？ 
 
 
 
 发自我的iPhone 
 
 
 ------------------ Original ------------------ 
 From: duronxx ***@***.***&amp;gt; 
 Date: Mon,Nov 8,2021 8:51 PM 
 To: welliamcao/OpsManage ***@***.***&amp;gt; 
 Cc: Subscribed ***@***.***&amp;gt; 
 Subject: Re: [welliamcao/OpsManage] Server Error (500) (Issue #330) 
 
 
 
 
 
   
 请问下是那里出问题了？ 
   
 ops_web     | The above exception was the direct cause of the following exception: 
  ops_web     | 
  ops_web     | Traceback (most recent call last): 
  ops_web     |   File &quot;manage.py&quot;, line 23, in  
  ops_web     |     execute_from_command_line(sys.argv) 
  ops_web     |   File &quot;/usr/local/lib/python3.6/site-packages/django/core/management/init.py&quot;, line 381, in execute_from_command_line 
  ops_web     |     utility.execute() 
  ops_web     |   File &quot;/usr/local/lib/python3.6/site-packages/django/core/management/init.py&quot;, line 375, in execute 
  ops_web     |     self.fetch_command(subcommand).run_from_argv(self.argv) 
  ops_web     |   File &quot;/usr/local/lib/python3.6/site-packages/django/core/management/base.py&quot;, line 323, in run_from_argv 
  ops_web     |     self.execute(*args, **cmd_options) 
  ops_web     |   File &quot;/usr/local/lib/python3.6/site-packages/django/core/management/base.py&quot;, line 364, in execute 
  ops_web     |     output = self.handle(*args, **options) 
  ops_web     |   File &quot;/usr/local/lib/python3.6/site-packages/django/core/management/commands/loaddata.py&quot;, line 72, in handle 
  ops_web     |     self.loaddata(fixture_labels) 
  ops_web     |   File &quot;/usr/local/lib/python3.6/site-packages/django/core/management/commands/loaddata.py&quot;, line 114, in loaddata 
  ops_web     |     self.load_label(fixture_label) 
  ops_web     |   File &quot;/usr/local/lib/python3.6/site-packages/django/core/management/commands/loaddata.py&quot;, line 181, in load_label 
  ops_web     |     obj.save(using=self.using) 
  ops_web     |   File &quot;/usr/local/lib/python3.6/site-packages/django/core/serializers/base.py&quot;, line 223, in save 
  ops_web     |     models.Model.save_base(self.object, using=using, raw=True, **kwargs) 
  ops_web     |   File &quot;/usr/local/lib/python3.6/site-packages/django/db/models/base.py&quot;, line 779, in save_base 
  ops_web     |     force_update, using, update_fields, 
  ops_web     |   File &quot;/usr/local/lib/python3.6/site-packages/django/db/models/base.py&quot;, line 851, in _save_table 
  ops_web     |     forced_update) 
  ops_web     |   File &quot;/usr/local/lib/python3.6/site-packages/django/db/models/base.py&quot;, line 900, in _do_update 
  ops_web     |     return filtered._update(values) &amp;gt; 0 
  ops_web     |   File &quot;/usr/local/lib/python3.6/site-packages/django/db/models/query.py&quot;, line 760, in _update 
  ops_web     |     return query.get_compiler(self.db).execute_sql(CURSOR) 
  ops_web     |   File &quot;/usr/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py&quot;, line 1469, in execute_sql 
  ops_web     |     cursor = super().execute_sql(result_type) 
  ops_web     |   File &quot;/usr/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py&quot;, line 1140, in execute_sql 
  ops_web     |     cursor.execute(sql, params) 
  ops_web     |   File &quot;/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py&quot;, line 67, in execute 
  ops_web     |     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute) 
  ops_web     |   File &quot;/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py&quot;, line 76, in _execute_with_wrappers 
  ops_web     |     return executor(sql, params, many, context) 
  ops_web     |   File &quot;/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py&quot;, line 84, in _execute 
  ops_web     |     return self.cursor.execute(sql, params) 
  ops_web     |   File &quot;/usr/local/lib/python3.6/site-packages/django/db/utils.py&quot;, line 89, in exit 
  ops_web     |     raise dj_exc_value.with_traceback(traceback) from exc_value 
  ops_web     |   File &quot;/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py&quot;, line 84, in _execute 
  ops_web     |     return self.cursor.execute(sql, params) 
  ops_web     |   File &quot;/usr/local/lib/python3.6/site-packages/django/db/backends/mysql/base.py&quot;, line 71, in execute 
  ops_web     |     return self.cursor.execute(query, args) 
  ops_web     |   File &quot;/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py&quot;, line 250, in execute 
  ops_web     |     self.errorhandler(self, exc, value) 
  ops_web     |   File &quot;/usr/local/lib/python3.6/site-packages/MySQLdb/connections.py&quot;, line 50, in defaulterrorhandler 
  ops_web     |     raise errorvalue 
  ops_web     |   File &quot;/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py&quot;, line 247, in execute 
  ops_web     |     res = self._query(query) 
  ops_web     |   File &quot;/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py&quot;, line 412, in _query 
  ops_web     |     rowcount = self._do_query(q) 
  ops_web     |   File &quot;/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py&quot;, line 375, in _do_query 
  ops_web     |     db.query(q) 
  ops_web     |   File &quot;/usr/local/lib/python3.6/site-packages/MySQLdb/connections.py&quot;, line 276, in query 
  ops_web     |     _mysql.connection.query(self, query) 
  ops_web     | django.db.utils.ProgrammingError: Problem installing fixture '/data/apps/opsmanage/docker/superuser.json': Could not load auth.User(pk=1): (1146, &quot;Table 'opsmanage.auth_user' doesn't exist&quot;) 
  ops_web     | Unlinking stale socket /tmp/supervisor.sock 
  ops_web     | 2021-11-08 20:34:26 [INFO] server.py[line:106] HTTP/2 support not enabled (install the http2 and tls Twisted extras) 
  ops_web     | 2021-11-08 20:34:26 [INFO] server.py[line:113] Configuring endpoint tcp:port=8000:interface=0.0.0.0 
  ops_web     | 2021-11-08 20:34:26 [INFO] server.py[line:144] Listening on TCP address 0.0.0.0:8000 
  ops_web     | 2021-11-08 20:35:21 [INFO] runserver.py[line:147] HTTP GET / 302 [0.05, 192.168.0.240:3204] 
  ops_web     | 2021-11-08 20:35:21 [ERROR] runserver.py[line:154] HTTP GET /login/?next=/ 500 [0.05, 192.168.0.240:3204] 
  ops_web     | 2021-11-08 20:39:41 [INFO] runserver.py[line:147] HTTP GET / 302 [0.01, 192.168.0.240:4576] 
  ops_web     | 2021-11-08 20:39:41 [ERROR] runserver.py[line:154] HTTP GET /login/?next=/ 500 [0.01, 192.168.0.240:4576] 
  ops_web     | 2021-11-08 20:39:41 [INFO] runserver.py[line:147] HTTP GET / 302 [0.00, 192.168.0.240:4576] 
  ops_web     | 2021-11-08 20:39:41 [ERROR] runserver.py[line:154] HTTP GET /login/?next=/ 500 [0.01, 192.168.0.240:4576] 
   
 — 
 You are receiving this because you are subscribed to this thread. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 Triage notifications on the go with GitHub Mobile for iOS or Android. 
&mdash;
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by welliamcao** [comment]
对，你用安装文档里面的方法部署吧，不要用docker



发自我的iPhone


------------------ Original ------------------
From: duronxx ***@***.***&gt;
Date: Mon,Nov 8,2021 9:08 PM
To: welliamcao/OpsManage ***@***.***&gt;
Cc: William.Cao ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [welliamcao/OpsManage] Server Error (500) (Issue #330)





 是的，数据库的表吗。 
 
 
 ---Original--- 
 From: ***@***.***&amp;gt; 
 Date: Mon, Nov 8, 2021 21:07 PM 
 To: ***@***.***&amp;gt;; 
 Cc: ***@***.******@***.***&amp;gt;; 
 Subject: Re: [welliamcao/OpsManage] Server Error (500) (Issue #330) 
 
 
 
 
  表不存在，你用docker部署的吗？  
   
   
   
  发自我的iPhone  
   
   
  ------------------ Original ------------------  
  From: duronxx ***@***.***&amp;amp;gt;  
  Date: Mon,Nov 8,2021 8:51 PM  
  To: welliamcao/OpsManage ***@***.***&amp;amp;gt;  
  Cc: Subscribed ***@***.***&amp;amp;gt;  
  Subject: Re: [welliamcao/OpsManage] Server Error (500) (Issue #330)  
   
   
   
   
   
     
  请问下是那里出问题了？  
     
  ops_web     | The above exception was the direct cause of the following exception:  
   ops_web     |  
   ops_web     | Traceback (most recent call last):  
   ops_web     |   File &amp;quot;manage.py&amp;quot;, line 23, in   
   ops_web     |     execute_from_command_line(sys.argv)  
   ops_web     |   File &amp;quot;/usr/local/lib/python3.6/site-packages/django/core/management/init.py&amp;quot;, line 381, in execute_from_command_line  
   ops_web     |     utility.execute()  
   ops_web     |   File &amp;quot;/usr/local/lib/python3.6/site-packages/django/core/management/init.py&amp;quot;, line 375, in execute  
   ops_web     |     self.fetch_command(subcommand).run_from_argv(self.argv)  
   ops_web     |   File &amp;quot;/usr/local/lib/python3.6/site-packages/django/core/management/base.py&amp;quot;, line 323, in run_from_argv  
   ops_web     |     self.execute(*args, **cmd_options)  
   ops_web     |   File &amp;quot;/usr/local/lib/python3.6/site-packages/django/core/management/base.py&amp;quot;, line 364, in execute  
   ops_web     |     output = self.handle(*args, **options)  
   ops_web     |   File &amp;quot;/usr/local/lib/python3.6/site-packages/django/core/management/commands/loaddata.py&amp;quot;, line 72, in handle  
   ops_web     |     self.loaddata(fixture_labels)  
   ops_web     |   File &amp;quot;/usr/local/lib/python3.6/site-packages/django/core/management/commands/loaddata.py&amp;quot;, line 114, in loaddata  
   ops_web     |     self.load_label(fixture_label)  
   ops_web     |   File &amp;quot;/usr/local/lib/python3.6/site-packages/django/core/management/commands/loaddata.py&amp;quot;, line 181, in load_label  
   ops_web     |     obj.save(using=self.using)  
   ops_web     |   File &amp;quot;/usr/local/lib/python3.6/site-packages/django/core/serializers/base.py&amp;quot;, line 223, in save  
   ops_web     |     models.Model.save_base(self.object, using=using, raw=True, **kwargs)  
   ops_web     |   File &amp;quot;/usr/local/lib/python3.6/site-packages/django/db/models/base.py&amp;quot;, line 779, in save_base  
   ops_web     |     force_update, using, update_fields,  
   ops_web     |   File &amp;quot;/usr/local/lib/python3.6/site-packages/django/db/models/base.py&amp;quot;, line 851, in _save_table  
   ops_web     |     forced_update)  
   ops_web     |   File &amp;quot;/usr/local/lib/python3.6/site-packages/django/db/models/base.py&amp;quot;, line 900, in _do_update  
   ops_web     |     return filtered._update(values) &amp;amp;gt; 0  
   ops_web     |   File &amp;quot;/usr/local/lib/python3.6/site-packages/django/db/models/query.py&amp;quot;, line 760, in _update  
   ops_web     |     return query.get_compiler(self.db).execute_sql(CURSOR)  
   ops_web     |   File &amp;quot;/usr/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py&amp;quot;, line 1469, in execute_sql  
   ops_web     |     cursor = super().execute_sql(result_type)  
   ops_web     |   File &amp;quot;/usr/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py&amp;quot;, line 1140, in execute_sql  
   ops_web     |     cursor.execute(sql, params)  
   ops_web     |   File &amp;quot;/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py&amp;quot;, line 67, in execute  
   ops_web     |     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)  
   ops_web     |   File &amp;quot;/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py&amp;quot;, line 76, in _execute_with_wrappers  
   ops_web     |     return executor(sql, params, many, context)  
   ops_web     |   File &amp;quot;/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py&amp;quot;, line 84, in _execute  
   ops_web     |     return self.cursor.execute(sql, params)  
   ops_web     |   File &amp;quot;/usr/local/lib/python3.6/site-packages/django/db/utils.py&amp;quot;, line 89, in exit  
   ops_web     |     raise dj_exc_value.with_traceback(traceback) from exc_value  
   ops_web     |   File &amp;quot;/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py&amp;quot;, line 84, in _execute  
   ops_web     |     return self.cursor.execute(sql, params)  
   ops_web     |   File &amp;quot;/usr/local/lib/python3.6/site-packages/django/db/backends/mysql/base.py&amp;quot;, line 71, in execute  
   ops_web     |     return self.cursor.execute(query, args)  
   ops_web     |   File &amp;quot;/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py&amp;quot;, line 250, in execute  
   ops_web     |     self.errorhandler(self, exc, value)  
   ops_web     |   File &amp;quot;/usr/local/lib/python3.6/site-packages/MySQLdb/connections.py&amp;quot;, line 50, in defaulterrorhandler  
   ops_web     |     raise errorvalue  
   ops_web     |   File &amp;quot;/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py&amp;quot;, line 247, in execute  
   ops_web     |     res = self._query(query)  
   ops_web     |   File &amp;quot;/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py&amp;quot;, line 412, in _query  
   ops_web     |     rowcount = self._do_query(q)  
   ops_web     |   File &amp;quot;/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py&amp;quot;, line 375, in _do_query  
   ops_web     |     db.query(q)  
   ops_web     |   File &amp;quot;/usr/local/lib/python3.6/site-packages/MySQLdb/connections.py&amp;quot;, line 276, in query  
   ops_web     |     _mysql.connection.query(self, query)  
   ops_web     | django.db.utils.ProgrammingError: Problem installing fixture '/data/apps/opsmanage/docker/superuser.json': Could not load auth.User(pk=1): (1146, &amp;quot;Table 'opsmanage.auth_user' doesn't exist&amp;quot;)  
   ops_web     | Unlinking stale socket /tmp/supervisor.sock  
   ops_web     | 2021-11-08 20:34:26 [INFO] server.py[line:106] HTTP/2 support not enabled (install the http2 and tls Twisted extras)  
   ops_web     | 2021-11-08 20:34:26 [INFO] server.py[line:113] Configuring endpoint tcp:port=8000:interface=0.0.0.0  
   ops_web     | 2021-11-08 20:34:26 [INFO] server.py[line:144] Listening on TCP address 0.0.0.0:8000  
   ops_web     | 2021-11-08 20:35:21 [INFO] runserver.py[line:147] HTTP GET / 302 [0.05, 192.168.0.240:3204]  
   ops_web     | 2021-11-08 20:35:21 [ERROR] runserver.py[line:154] HTTP GET /login/?next=/ 500 [0.05, 192.168.0.240:3204]  
   ops_web     | 2021-11-08 20:39:41 [INFO] runserver.py[line:147] HTTP GET / 302 [0.01, 192.168.0.240:4576]  
   ops_web     | 2021-11-08 20:39:41 [ERROR] runserver.py[line:154] HTTP GET /login/?next=/ 500 [0.01, 192.168.0.240:4576]  
   ops_web     | 2021-11-08 20:39:41 [INFO] runserver.py[line:147] HTTP GET / 302 [0.00, 192.168.0.240:4576]  
   ops_web     | 2021-11-08 20:39:41 [ERROR] runserver.py[line:154] HTTP GET /login/?next=/ 500 [0.01, 192.168.0.240:4576]  
     
  —  
  You are receiving this because you are subscribed to this thread.  
  Reply to this email directly, view it on GitHub, or unsubscribe.  
  Triage notifications on the go with GitHub Mobile for iOS or Android.  
 &amp;mdash; 
 You are receiving this because you authored the thread. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 Triage notifications on the go with GitHub Mobile for iOS or Android. 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
