### ISSUE TITLE
项目点击初始化失败

### ISSUE THREAD

**Issue by JuneyQiu** [welliamcao/OpsManage#338]
新建项目，在点击初始化失败，报错信息如下：
GitCommandError at /apps/config/
Cmd('git') failed due to: exit code(128)
cmdline: **git clone -v git@gitlab.tools.baowei-inc.com:SMP/smp-b2b.git /apps/Deploy/source/portal-pre.baowei-inc.com/**
stderr: 'Host key verification failed.
fatal: The remote end hung up unexpectedly
'

Request Method: POST
Request URL: http://cmdb.tools.baowei-inc.com/apps/config/
Django Version: 2.2.15
Python Executable: /apps/svr/OpsManage/python/bin/python3
Python Version: 3.6.8
Python Path: ['/data/apps/svr/OpsManage-3.0.4', '/apps/svr/OpsManage/python/lib/python3.6/site-packages/git/ext/gitdb', '/data/apps/svr/OpsManage-3.0.4/apps', '/data/apps/svr/OpsManage-3.0.4', '/apps/svr/python/lib/python36.zip', '/apps/svr/python/lib/python3.6', '/apps/svr/python/lib/python3.6/lib-dynload', '/apps/svr/OpsManage/python/lib/python3.6/site-packages', '/apps/svr/OpsManage/python/lib/python3.6/site-packages/gitdb/ext/smmap']
Server time: Tue, 8 Feb 2022 15:07:26 +0800
Installed Applications:
['django.contrib.admin',
'django.contrib.auth',
'django.contrib.contenttypes',
'django.contrib.sessions',
'django.contrib.messages',
'django.contrib.staticfiles',
'rest_framework',
'mptt',
'channels',
'OpsManage',
'navbar',
'databases',
'asset',

手动在主机执行命令是可以拉取代码的：git clone -v git@gitlab.tools.baowei-inc.com:SMP/smp-b2b.git /apps/Deploy/source/portal-pre.baowei-inc.com/

资产管理-主机信息更新正
<img width="810" alt="portal-pre初始化失败" src="https://user-images.githubusercontent.com/28282404/152936472-bed27d0c-3ecb-4590-a151-7e5d34a0124a.png">
常

**Comment by JuneyQiu** [comment]
<img width="804" alt="报错详细信息2" src="https://user-images.githubusercontent.com/28282404/152937640-e85f1995-7813-492c-b37f-bd963a36fc5a.png">

**Comment by welliamcao** [comment]
git认证失败了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: JuneyQiu ***@***.***&gt;
发送时间: 2022年2月8日 15:13
收件人: welliamcao/OpsManage ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [welliamcao/OpsManage] 项目点击初始化失败 (Issue #338)






新建项目，在点击初始化失败，报错信息如下：
GitCommandError at /apps/config/
Cmd('git') failed due to: exit code(128)
cmdline: git clone -v ***@***.***:SMP/smp-b2b.git /apps/Deploy/source/portal-pre.baowei-inc.com/
stderr: 'Host key verification failed.
fatal: The remote end hung up unexpectedly
'

Request Method: POST
Request URL: http://cmdb.tools.baowei-inc.com/apps/config/
Django Version: 2.2.15
Python Executable: /apps/svr/OpsManage/python/bin/python3
Python Version: 3.6.8
Python Path: ['/data/apps/svr/OpsManage-3.0.4', '/apps/svr/OpsManage/python/lib/python3.6/site-packages/git/ext/gitdb', '/data/apps/svr/OpsManage-3.0.4/apps', '/data/apps/svr/OpsManage-3.0.4', '/apps/svr/python/lib/python36.zip', '/apps/svr/python/lib/python3.6', '/apps/svr/python/lib/python3.6/lib-dynload', '/apps/svr/OpsManage/python/lib/python3.6/site-packages', '/apps/svr/OpsManage/python/lib/python3.6/site-packages/gitdb/ext/smmap']
Server time: Tue, 8 Feb 2022 15:07:26 +0800
Installed Applications:
['django.contrib.admin',
'django.contrib.auth',
'django.contrib.contenttypes',
'django.contrib.sessions',
'django.contrib.messages',
'django.contrib.staticfiles',
'rest_framework',
'mptt',
'channels',
'OpsManage',
'navbar',
'databases',
'asset',

手动在主机执行命令是可以拉取代码的：git clone -v ***@***.***:SMP/smp-b2b.git /apps/Deploy/source/portal-pre.baowei-inc.com/

资产管理-主机信息更新正

常

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
